FourthWebApp/Controllers/ShowTimeController.cs
using Data_Access;
using FourthWebApp.Controllers;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Runtime.Remoting.Messaging;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ViewModel;
using static Kendo.Mvc.UI.UIPrimitives;

namespace MvcMovie.Controllers
{
    public class ShowTimeController : BaseController
    {

        ShowTimeDalSql _ShowTimeDalSql = new ShowTimeDalSql();
        //AccountDalSql _accountDalSql = new AccountDalSql();
        // GET: ShowTime
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult GetShowTime([DataSourceRequest] DataSourceRequest request, bool showAll = false)
        {
            DateTime currentDate = DateTime.Now;
            List<ShowTimeViewModel> movie;

            if (showAll)
            {
                movie = _ShowTimeDalSql.GetShowTimeForKendoGrid();
            }
            else
            {
                movie = _ShowTimeDalSql.GetShowTimeForKendoGrid()
                    .Where(c => c.EndDate > currentDate)
                     .ToList() ;
            }


            return Json(movie.ToDataSourceResult(request));
        }

        public ActionResult GetMovies([DataSourceRequest] DataSourceRequest request)
        {
            List<MovieViewModel> movies = _ShowTimeDalSql.GetMovieForKendoGrid();

            return Json(movies, JsonRequestBehavior.AllowGet);
        }




        public ActionResult Manage(int showTimeId = 0)
        {
            ShowTimeViewModel show = new ShowTimeViewModel();
            

                if(showTimeId != 0)
                {
                     show = _ShowTimeDalSql.GetShowViewModel(showTimeId); 
                     

                    if (show == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                    show.StartDateString = show.StartDate.ToString("MM/dd/yyyy");
                    show.EndDateString = show.EndDate.ToString("MM/dd/yyyy");
                    }
                
                }

                else
                {
                
                show.StartDateString = show.StartDate.ToString("MM/dd/yyyy");
                show.EndDateString = show.EndDate.ToString("MM/dd/yyyy");
                }
            return View(show);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(ShowTimeViewModel model)
        {
            
            if (model.ShowTimeId == 0)
                {
                model.CreatedBy = (int)Session["UserId"];
                _ShowTimeDalSql.CreateShowTime(model);
                 
                }
                else
                {
                  _ShowTimeDalSql.UpdateShowTime(model);
                   
                }
            return JavaScript("CloseManageShowTime()");
        }

        public ActionResult BookTicket(int showTimeId)
        {
            var existingShowTime = _ShowTimeDalSql.GetShowViewModel(showTimeId);
            var showtimes = _ShowTimeDalSql.GetTimesForKendoGrid(showTimeId);

            // showtime values as a list
            var showtimeList = showtimes.FirstOrDefault();
            int userId = (int)Session["UserId"];
            //int userType = _accountDalSql.GetUserTypeByUserId(userId);

            //ViewBag.UserType = userType;
            // list of SelectListItem with three options
            var showtimeOptions = new List<Kendo.Mvc.UI.DropDownListItem>
    {
        new Kendo.Mvc.UI.DropDownListItem
        {
            Text = showtimeList.FirstShowTime,
            Value = showtimeList.FirstShowTime
        },
        new Kendo.Mvc.UI.DropDownListItem
        {
            Text = showtimeList.SecondShowTime,
            Value = showtimeList.SecondShowTime
        },
        new Kendo.Mvc.UI.DropDownListItem
        {
            Text = showtimeList.ThirdShowTime,
            Value = showtimeList.ThirdShowTime
        }
    };

            ViewBag.ShowtimeOptions = showtimeOptions;

            
            existingShowTime.SelectedShowtime = showtimeList.FirstShowTime;

            var seatTypes = _ShowTimeDalSql.GetSeatTypes();

            var seatTypeOptions = seatTypes.Select(seatType => new SelectListItem
            {
                Text = $"{seatType.TypeName} - Rs {seatType.Price}",
                Value = seatType.TypeName 
            }).ToList();
           

            // Default value for SelectedSeatType
            existingShowTime.SelectedSeatType = "Normal - Rs 200";

            
            existingShowTime.SeatTypeOptions = seatTypeOptions;

            return View(existingShowTime);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BookTicket(ShowTimeViewModel model)
        {
           
                
                    var seatTypesId = _ShowTimeDalSql.GetSeatTypesId(model.SelectedSeatType);

                    // Update the properties of the existing model
                    model.MovieId = model.MovieId;
                    //model.ShowDate = model.SelectedDate;
                    
                    model.ShowTime = model.SelectedShowtime;
                    model.TypeName = model.SelectedSeatType;
                    model.SeatTypeId = seatTypesId;
                    model.PaymentStatus = 1;
                    model.PaymentAmount = _ShowTimeDalSql.CalculatePaymentAmount(seatTypesId, model.TicketCount);
                    model.NoOfTicket = model.TicketCount;
                    model.UserId = (int)Session["UserId"];
            //int id = model.MovieId;
            //int userId = model.UserId;
            //var seatTypeName = model.TypeName;
            //var payment = model.PaymentStatus;
            //var amount = model.PaymentAmount;
            //var NoOfTicket = model.NoOfTicket; 

            var seatTypes = _ShowTimeDalSql.GetSeatTypes();
                    var radioGroupOptions = seatTypes.Select(seatType => $"{seatType.TypeName} - Rs {seatType.Price}").ToArray();
                    ViewBag.SeatTypeOptions = radioGroupOptions;

                    int id =_ShowTimeDalSql.SaveBookTicket(model);




            return JavaScript($"CloseBookShow({id})");

        }
        public ActionResult BookingSuccessfull(int id)
        {
            ViewBag.PrintId = id;
            return View();

        }


        public void PrintTictetToPdf(int id)
        {
            

            string htmlString = GetPrintTicketPdf(id);
            var generator = new NReco.PdfGenerator.HtmlToPdfConverter();
            
            var pdfBytes = generator.GeneratePdf(htmlString);
            Response.ContentType = "application/pdf";
            Response.ContentEncoding = System.Text.Encoding.UTF8;
            Response.AddHeader("Content-Disposition", "Inline; filename=" + "PrintTicket.pdf");
            Response.BinaryWrite(pdfBytes);
            Response.Flush();
            Response.End();
        }

        private string GetPrintTicketPdf(int id)
        {
            ShowTimeViewModel view = _ShowTimeDalSql.GetBookingsInfo(id);

            StringBuilder sb = new StringBuilder();

            sb.Append("<div><img src='" + view.MovieImage + "' style='width: 100px; height: 100px;'/></div>");

            sb.Append("-------------------------------------------------------------------------------------------------------------------------------");

            sb.Append("<div style='text-align:left; font-size:30px;'><b>" + view.Title + "</b></div>");
            sb.Append("<div>" + "( " + view.LanguageName + " )" + "</div>");
            sb.Append("-------------------------------------------------------------------------------------------------------------------------------");

            sb.Append("<table style='width:100%'>");
            sb.Append("<tr><td style='text-align:left; font-size:18px;'>" + "Date" + "</td>");
            sb.Append("<td style='text-align:center; font-size:18px;'>" + "Time" + "</td></tr>");
            sb.Append("</table>");

            sb.Append("<table style='width:100%'>");
            sb.Append("<tr><td style='text-align:left; font-size:18px; font-weight:bold;'>" + view.ShowDate.ToString("ddd, dd MMM, yyyy") + "</td>");
            sb.Append("<td style='text-align:center; font-size:18px; font-weight:bold;'>" + view.ShowTime + "</td></tr>");
            sb.Append("</table>");

            sb.Append("-------------------------------------------------------------------------------------------------------------------------------");

            sb.Append("<table style='width:100%'>");
            sb.Append("<tr><td style='text-align:left; font-size:18px;'>" + "Seats" + "</td>");
            sb.Append("<td style='text-align:center; font-size:18px;'>" + "No. of Tickets" + "</td></tr>");
            sb.Append("</table>");

            sb.Append("<table style='width:100%'>");
            sb.Append("<tr><td style='text-align:left; font-size:25px; font-weight:bold;'>" + view.TypeName + "</td>");
            sb.Append("<td style='font-size:25px; font-weight:bold;'>" + view.NoOfTicket + "</td></tr>");
            sb.Append("</table>");

            return sb.ToString();
        }




        public string DeleteShow(int showTimeId)
        {
            string msg = "";
            try
            {
                _ShowTimeDalSql.DeleteConfirm(showTimeId);
                msg = "Ok";
            }
            catch (Exception e)
            {
                msg = "ERROR : " + e.Message;
            }
            return msg;
        }


        public ActionResult BookTicketIndex()
        {
            int userId = (int)Session["UserId"];
            //int userType = _accountDalSql.GetUserTypeByUserId(userId);

FourthWebApp/Views/ShowTime/BookTicket.cshtml
@model ViewModel.ShowTimeViewModel
@using Kendo.Mvc.UI

<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@{
    Layout = null;
    ViewBag.Title = "BookTicket";
}


@using (Ajax.BeginForm("BookTicket", "ShowTime",
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "ajax_contentMain"
    }, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.ShowTimeId, new { id = "ShowTimeId" })
    @Html.HiddenFor(model => model.MovieId, new { id = "MovieId" })
    @Html.HiddenFor(model => model.StartDate, new { id = "StartDate" })
    @Html.HiddenFor(model => model.ShowDateString, new { id = "ShowDateString" })
    @Html.HiddenFor(model => model.SelectedDate, new { id = "SelectedDate" })
    @Html.HiddenFor(model => model.SelectedTime, new { id = "SelectedTime" })
    @Html.HiddenFor(model => model.SelectedSeat, new { id = "ShowTimeId" })
    @Html.HiddenFor(model => model.TicketCount, new { id = "TicketCount" })
    @Html.HiddenFor(model => model.SeatTypeOptions, new { id = "SeatTypeOptions" })




    <h2>@Model.Title</h2>


    <div id="selectDate">
        <div class="k-d-flex k-justify-content" style="padding-bottom: 30px;">
            <div class="k-w-300">
                <label>Select a Date:</label>
                @(Html.Kendo().DatePicker()
            .Name("datepickerTicket")
            .Value(Model.StartDate)
            .Min(Model.StartDate)
            .Max(Model.StartDate.AddDays(3))
            )
            </div>
        </div>
    </div>



    <div id="selectTime" style="padding-bottom: 30px;">
        <label for="Showtime">Select Showtime:</label>
        @(Html.Kendo().DropDownListFor(m => m.SelectedShowtime)
        //.Name("timeDropTicket")
        .Name("SelectedShowtime")
            .DataTextField("Text")
            .DataValueField("Value")
            //.BindTo((IEnumerable<Kendo.Mvc.UI.DropDownListItem>)ViewBag.ShowtimeOptions)
            .BindTo(new List<SelectListItem>()
            {
                new SelectListItem() {
                  Text = Model.FirstShowTime,
                  Value = Model.FirstShowTime
              },
              new SelectListItem() {
                  Text = Model.SecondShowTime,
                  Value = Model.SecondShowTime
              },
              new SelectListItem() {
                  Text = Model.ThirdShowTime,
                  Value = Model.ThirdShowTime
              }
            })
            .Value(Model.FirstShowTime)

        )

    </div>

    @*<div class="demo-section" id="selectSeat" style="padding-bottom: 30px;">
        <label for="radiogroup" class="label">Select Seat Type:</label>

        @foreach (var seatType in Model.SeatTypeOptions)
        {
            <label>
                <input type="radio" name="SelectedSeatType" value="@seatType.Value" @(Model.SelectedSeatType == seatType.Value ? "checked" : "") />
                @seatType.Text
            </label>
        }
    </div>*@

    <div class="demo-section" id="selectSeat" style="padding-bottom: 30px;">
        <label for="radiogroup" class="label">Select Seat Type:</label>

        @foreach (var seatType in Model.SeatTypeOptions)
        {
            <label>
                <input type="radio" name="SelectedSeatType" value="@seatType.Value" @(Model.SelectedSeatType == seatType.Value ? "checked" : "") />
                @seatType.Text
            </label>
        }
    </div>




    <div id="selectTicketQuantity" style="padding-bottom: 30px;">
        <label for="TicketQuantity">Select Number of Tickets:</label>
        @(Html.Kendo().NumericTextBoxFor(m => m.TicketQuantity)
        .Name("countTicket")
        .Min(1)
        .Max(10)
        .Value(1)
        .HtmlAttributes(new { style = "width: 100px;" })
        .Format("n0")
    )
    </div>






    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" onclick="BookTicket()" />
    </div>

}

<script>

    function BookTicket() {
        var ticketDate = $('#datepickerTicket').val();
        var ticketTime = $('#SelectedShowtime').val();
        var ticketSeat = $('input[name="SelectedSeatType"]:checked').val();
        var ticketCount = $('#countTicket').val();

        //alert(ticketDate);
        //alert(ticketTime);
        //alert(ticketSeat);
        //alert(ticketCount);

        $("#TicketCount").val(ticketCount);
        $("#ShowDateString").val(ticketDate);
    }

</script>

FourthWebApp/Views/ShowTime/BookingSuccessfull.cshtml
@model ViewModel.ShowTimeViewModel
@{
    ViewBag.Title = "BookingSuccessful";
    Layout = null;
}
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<div> <p> yay! Your Booking is successful</p></div>

<div style="float:right; padding-top:15px; padding-bottom:5px"><button class="btn btn-sm btn-primary" onclick="PrintTicket()">Print Ticket</button></div>
<script>

    //alert(id);


    function PrintTicket() {


        
    var id = '@ViewBag.PrintId';


    url = "/ShowTime/PrintTictetToPdf?id=" + id;
    window.open(url, '_blank');
}




</script>

FourthWebApp/Views/ShowTime/Manage.cshtml
@model ViewModel.ShowTimeViewModel
@using Kendo.Mvc.UI
@using System.Web.Mvc
@{
    Layout = null;
    ViewBag.Title = "ManageShowTime";
}
<link href="~/assets4.1/libs/clockpicker/bootstrap-clockpicker.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets4.1/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script>

    $(document).ready(function () {


        $('#datepickerStartGrid').datepicker({
            autoclose: true,
            todayHighlight: true,
        });

        $('#datepickerEndGrid').datepicker({
            autoclose: true,
            todayHighlight: true,
        });

        if ('@Model.StartDateString' != '') {

            var startDateNew = new Date('@Model.StartDateString');
            var dateOne = (moment(startDateNew).format('MM/DD/YYYY'));

            $('#datepickerStartGrid').val(dateOne);
            $('#datepickerStartGrid').datepicker("setDate", dateOne);


        }

        if ('@Model.EndDateString' != '') {

    var endDateNew = new Date('@Model.EndDateString');
    var dateTwo = (moment(endDateNew).format('MM/DD/YYYY'));

            $('#datepickerEndGrid').val(dateTwo);
            $('#datepickerEndGrid').datepicker("setDate", dateTwo);
        }

        if ('@Model.FirstShowTime' != '') {
    var timeOne = '@Model.FirstShowTime'; // Assuming '@Model.FirstShowTime' is in 'hh:mm tt' format.

    $('#timepickerFirst').val(timeOne); // Set the value of the input element

    // Initialize ClockPicker and set the time
    $('#timepickerFirst').clockpicker('show').clockpicker('pop');
}

        @*if ('@Model.SecondShowTime' != '') {

            var secondShowNew = new Date('1/1/2023 @Model.SecondShowTime');
            var timeTwo = (moment(secondShowNew).format('hh:mm A'));

            $('#timepickerSecond').val(timeTwo);
            $('#timepickerSecond').clockpicker("setDate", timeTwo);
        }*@
        if ('@Model.SecondShowTime' != '') {
    var timeTwo = '@Model.SecondShowTime';

    $('#timepickerSecond').val(timeTwo);


    $('#timepickerSecond').clockpicker('show').clockpicker('pop');
}





        if ('@Model.ThirdShowTime' != '') {
    var timeThree = '@Model.ThirdShowTime';

    $('#timepickerThird').val(timeThree);


    $('#timepickerThird').clockpicker('show').clockpicker('pop');
}



    })

</script>

@Html.ValidationSummary(true)

@using (Ajax.BeginForm("Manage", "ShowTime",
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "ajax_contentMain"
    }, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.MovieId, new { id = "MovieId" })


    @Html.HiddenFor(model => model.ShowTimeId, new { id = "ShowTimeId" })
    @Html.HiddenFor(model => model.StartDateString, new { id = "StartDateString" })
    @Html.HiddenFor(model => model.EndDateString, new { id = "EndDateString" })
    @Html.HiddenFor(model => model.FirstShowTime, new { id = "FirstShowTime" })
    @Html.HiddenFor(model => model.SecondShowTime, new { id = "SecondShowTime" })
    @Html.HiddenFor(model => model.ThirdShowTime, new { id = "ThirdShowTime" })



    <div class="row">
        <div class="popup-col" id="dropTitle">
            @Html.HiddenFor(model => model.MovieId, new { id = "MovieId" })
            @Html.LabelFor(model => model.Title, new { @class = "control-label" })

            @if (Model.ShowTimeId > 0)
            {
                <label>@Model.Title</label>
                @Html.HiddenFor(model => model.Title) @* To preserve the value when submitting the form *@
            }
            else
            {
                @(Html.Kendo().DropDownList()
                .Name("titleDrop")
                .OptionLabel("Select a movie")
                .DataTextField("Title")
                .DataValueField("Id")
                .DataSource(source =>
                {
                    source.Read(read =>
                    {
                        read.Action("GetMovies", "ShowTime");
                    });
                })
            )
            }

            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            <span id="errorMsgTitle">@ViewBag.msg</span>
        </div>
        <div>
            <div class="popup-col-left">
                <div data-placement="bottom" data-align="top" data-autoclose="true" style="width: 300px; float: left; padding-right: 5px; padding-top: 20px;">
                    <label><strong>Select Start Date</strong></label><br />
                    @(Html.Kendo().DatePicker()
                .Name("datepickerStartGrid")
                .Format("MM/dd/yyyy")
                .HtmlAttributes(new { style = "width: 100%", title = "datepicker" })
            )
                </div>
                <span id="errorMsgDate1">@ViewBag.msg</span>
            </div>

            <div class="popup-col-right">
                <div data-placement="bottom" data-align="top" data-autoclose="true" style="width: 300px; padding-left: 5px; padding-top: 20px; float: right">
                    <label><strong>Select End Date</strong></label><br />
                    @(Html.Kendo().DatePicker()
                .Name("datepickerEndGrid")
                .Format("MM/dd/yyyy")
                .HtmlAttributes(new { style = "width: 100%", title = "datepicker" })
            )
                </div>
                <span id="errorMsgDate2">@ViewBag.msg</span>
            </div>
        </div>


        <div class="popup-col-left">

            <div class="input-group clockpicker" data-placement="bottom" data-align="top" data-autoclose="true" style="width: 33%; padding-left: 5px; float: right; padding-top: 30px">
                <label><strong>Select Third ShowTime</strong></label><br />
                @(Html.Kendo().TimePicker()
    .Name("timepickerThird")
    .Format("hh:mm tt")
    .HtmlAttributes(new { style = "width: 100%", title = "timepicker3" })
)
            </div>
            <span id="errorMsgTime1">@ViewBag.msg</span>

            <div class="input-group clockpicker" data-placement="bottom" data-align="top" data-autoclose="true" style="width: 33%; padding-left: 5px; float: right; padding-top: 30px">
                <label><strong>Select Second ShowTime</strong></label><br />
                @(Html.Kendo().TimePicker()
                .Name("timepickerSecond")
                .Format("hh:mm tt")
                .HtmlAttributes(new { style = "width: 100%", title = "timepicker2" })
            )
            </div>
            <span id="errorMsgTime2">@ViewBag.msg</span>
            <div class="input-group clockpicker" data-placement="bottom" data-align="top" data-autoclose="true" style="width: 33%; padding-left: 5px; float: right; padding-top: 30px">
                <label><strong>Select First ShowTime</strong></label><br />
                @(Html.Kendo().TimePicker()
    .Name("timepickerFirst")
    .Format("hh:mm tt")
    .HtmlAttributes(new { style = "width: 100%", title = "timepicker1" })
)
            </div>
            <span id="errorMsgTime3">@ViewBag.msg</span>

        </div>
    </div>

    <div class="popup-col-left">
        
    </div>
    <div class="popup-col-right" style="padding-top:45px; float: right; padding-right:2px">
        <div class="form-group">
            <span id="errorMsgSpan">@ViewBag.msg</span>
            @*<input type="submit" value="Save" class="btn btn-primary" onclick="ShowTimeAlert()" />*@
            <button type="submit" class="btn btn-success" id="btn" onclick="return ShowTimeAlert()">
                @(Model.ShowTimeId == 0 ? "Create" : "Save Changes")
            </button>
        </div>
</div>
        }

        <script>
    function ShowTimeAlert() {
        
        var startDate = $('#datepickerStartGrid').val();
        var endDate = $('#datepickerEndGrid').val();
        var firstShow = $('#timepickerFirst').val();
        var secondShow = $('#timepickerSecond').val();
        var thirdShow = $('#timepickerThird').val();

        var title = $('#titleDrop').val();

        

        clearErrorMessages();

        if (title == '') {
            displayErrorMessage('Please choose a show', 'errorMsgTitle')
            return false;
        }

        if (!isValidDate(startDate)) {
            displayErrorMessage('Please enter valid start date.', 'errorMsgSpan');
            return false;
        }
        if (!isValidDate(endDate)) {
            displayErrorMessage('Please enter valid end date.', 'errorMsgSpan');
            return false;
        }
        if (new Date(startDate) > new Date(endDate)) {
            displayErrorMessage('Start date must be less than end date.', 'errorMsgSpan');
            return false;
        }

        if (!isValidTime(firstShow)) {
            displayErrorMessage('Please enter a valid first show time.', 'errorMsgSpan');
            return false;
        }

        if (!isValidTime(secondShow)) {
            displayErrorMessage('Please enter a valid second show time.', 'errorMsgSpan');
            return false;
        }

        if (!isValidTime(thirdShow)) {
            displayErrorMessage('Please enter a valid third show time.', 'errorMsgSpan');
            return false;
        }

       

       

        clearErrorMessages();
        $("#StartDateString").val(startDate);
        $("#EndDateString").val(endDate);
        $("#FirstShowTime").val(firstShow);
        $("#SecondShowTime").val(secondShow);
        $("#ThirdShowTime").val(thirdShow);
        $("#MovieId").val(title);

        return true;


    }

            function clearErrorMessages() {
                // Clear all error messages
                $('#errorMsgSpan').text('');
                $('#errorMsgTitle').text('');
                $('#errorMsgDate1').text('');
                $('#errorMsgDate2').text('');
                $('#errorMsgTime1').text('');
                $('#errorMsgTime2').text('');
                $('#errorMsgTime3').text('');

            }

            function isValidDate(dateString) {
                // Check if the date string is in MM/DD/YYYY format
                var regex = /^\d{2}\/\d{2}\/\d{4}$/;
                return regex.test(dateString);
            }

            function isValidTime(timeString) {
                // Check if the time string is in "hh:mm tt" format
                var regex = /^(1[0-2]|0?[1-9]):[0-5][0-9] [APap][mM]$/;
                return regex.test(timeString);
            }

            function displayErrorMessage(message, elementId) {
                // Display error message in red below the specified element
                $('#' + elementId).text(message).css('color', 'red');
            }


        </script>

FourthWebApp/Views/ShowTime/MyBookings.cshtml
@using Kendo.Mvc.UI
@{
    ViewBag.Title = "MyBookings";
}

<h2>MyBookings</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div id="myBookingKendoGrid">
    @(Html.Kendo().Grid<ViewModel.ShowTimeViewModel>()
     .Name("myBookingGrid")
     .Columns(columns =>
     {
         columns.Bound(c => c.Title).Title("Show Name")/*.ClientTemplate("<div class='text-center' style='width:110px'><span id='spanName_#=MovieId#'>#=Title# </span></div>")*/.Width(100).Sortable(true).HeaderHtmlAttributes(new { style = "font-weight:bold;" });
         columns.Bound(c => c.SelectedDate).Title("Selected Date").Width(100).Sortable(true).HeaderHtmlAttributes(new { style = "font-weight:bold;" });
         columns.Bound(c => c.SelectedTime).Title("Selected Time").Width(100).Sortable(true).HeaderHtmlAttributes(new { style = "font-weight:bold;" });
         columns.Bound(c => c.SelectedSeat).Title("Selected Seat").Width(100).Sortable(true).HeaderHtmlAttributes(new { style = "font-weight:bold;" });
         columns.Bound(c => c.NoOfTicket).Title("No Of Ticket").Width(100).Sortable(true).HeaderHtmlAttributes(new { style = "font-weight:bold;" });
         columns.Bound(c => c.PaymentAmount).Title("Payment Amount").Width(100).Sortable(true).HeaderHtmlAttributes(new { style = "font-weight:bold;" });

         columns.Bound("").ClientTemplate(@"<a style='cursor: pointer' title='Print Ticket' onclick='PrintTicket(#=BookticketId#)'><i class='fa fa-print'></i></a>").Width(30).Sortable(false).Filterable(false);

         //columns.Bound("").ClientTemplate(@"<a style='cursor: pointer' title='Edit' onclick='ManageShow(#=BookTicketId#)' id='editAnchor_#=BookTicketId#'><i class='fa fa-pencil'></i></a>").Width(30).Sortable(false).Filterable(false);
         //columns.Bound("").ClientTemplate(@"<a style='cursor: pointer' title='Delete' onclick='DeleteShowTime(#=ShowTimeId#)'><i class='fa fa-trash'></i></a>").Width(30).Sortable(false).Filterable(false);



     })
     .Sortable()
     .DataSource(dataSource => dataSource
         .Ajax()
         .Read(read => read.Action("GetMyBookings", "ShowTime"))
     )
 )
</div>

<script>
    function PrintTicket(BookTicketId) {

    @*var id = '@ViewBag.PrintId';*@
        url = "/ShowTime/PrintTictetToPdf?id=" + BookTicketId;
    window.open(url, '_blank');
}
</script>